# A sample Gemfile
source "https://rubygems.org"

group :development, :test do
  gem 'pry'
  gem 'rspec'
  gem 'factory_girl'

  gem 'capybara'
  gem "capybara-webkit"
  gem 'turnip'
  gem 'poltergeist'

  gem 'docker-compose-api'
end
