jod:
  image: kaakaa/jodconverter
  command: tail -f > /dev/null

db:
  image: mongo

nginx:
  image: nginx
  ports:
    - "4567:80"
  links:
    - web:web
  volumes:
    - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

web:
  image: kaakaa/ppt-museum-web
  links:
    - db:db
    - jod:jod
