jod:
  build: ./jod/
  command: tail -f > /dev/null

db:
  image: mongo

nginx:
  image: nginx
  ports:
    - "4567:80"
  links:
    - web:web
  volumes:
    - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

web:
  image: java
  command: /bin/bash -c "/app/bin/ppt-museum"
  volumes:
    - ./ppt-museum/build/install/ppt-museum:/app
  links:
    - db:db
    - jod:jod
    - redis:redis

