jod:
  build: ./jod/
  ports:
    - "8080:8080"
  command: tail -f > /dev/null

db:
  image: mongo
  ports:
    - 27017:27017

web:
  image: qlik/gradle
  command: clean run -info
  ports:
    - "4567:4567"
  environment:
    GRADLE_VERSION: 2.10
  volumes:
    - ./web:/app
  links:
    - db:db
    - jod:jod
